services:
  # Your Application
  app:
    # Instead of 'image:', use 'build:' to point to your local code
    build: ../flight-checker  # Path to the folder containing your Dockerfile
    container_name: flight-checker-app
    restart: always
    volumes:
      - /home/richard/data:/app/data
    expose:
      - "8501"

  # Your Nginx Gateway
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth:/etc/nginx/auth:ro
    depends_on:
      - app