services:
  # Your Application Container
  app:
    build: 
      context: ../app
      dockerfile: dockerfile
    container_name: flight-checker-app
    restart: always
    volumes:
      # Mount the sibling 'data' folder on the host to the root '/data' folder inside the container
      - ../data:/data
    env_file:
      - .env
    environment:
      - INPUT_CSV=/data/source.csv
      - OUTPUT_CSV=/data/flights_output.csv
      - PARSE_CSV=/data/parse_output.csv
      - VERBOSE_LOGGING=True
    ports:
      - "8501:8501"

  # Your Nginx Gateway (Authentication Guard)
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth:/etc/nginx/auth:ro
    depends_on:
      - app